### ISSUE TITLE
bug in strategy mode ha

### ISSUE THREAD

**Issue by ricky1203** [nadoo/glider#142] opened 2019-12-27 12:13 UTC
in strategy.go initAvailable()
when no no forwarder available, will use the first one as default, but if the first one is always failed, it will never to disabled in check, so ha mode will always use the first forwarder

**Comment by bet4it** [comment] 2019-12-27 14:17
Duplicate of #135

**Comment by xlighting2017** [comment] 2019-12-30 04:06
what will be the expected result, if 
no other forwarders available && the first one is failed?

should we go "check regularly, hope the only/first one back to normal" (the current behavior)
or "disable the only fwder, stop the check"? (so, in other words, shutdown without letting you know until you manually check the logs)
or anything else? (you name it :))

**Comment by ricky1203** [comment] 2019-12-31 06:29
expect result: should check the first proxy to enable/disable the proxy 
the bug is that first one is not check when it is failed to disabled(onStatusChanged is not call), 

> what will be the expected result, if
> no other forwarders available && the first one is failed?
> 
> should we go "check regularly, hope the only/first one back to normal" (the current behavior)
> or "disable the only fwder, stop the check"? (so, in other words, shutdown without letting you know until you manually check the logs)
> or anything else? (you name it :))

**Comment by xlighting2017** [comment] 2019-12-31 07:05
what will happen, after that one(and also the only one) is disabled?
completely shutdown?

**Comment by nadoo** [comment] 2020-04-03 12:34
Thanks for your report, I think it was fixed in the latest commit.

**Closed by nadoo** 2020-04-03 12:34 UTC
Labels: bug
